### ISSUE TITLE
Starting the bridge throws ValueError("Invalid Homeserver") with homeserver https://matrix.mydomain.de:443

### ISSUE THREAD

**Issue by mikedolx** [i10b/matrix-matrix-bridge#4]
Hi,

after installing the bridge according to the README and creating a initial config.toml i tried to run the bridge with:

`sudo python -m poetry run main.py`

afterwards i get the following exception:

```
FileNotFoundError

  [Errno 2] No such file or directory: b'/snap/bin/main.py'

  at /usr/lib/python3.8/os.py:601 in _execvpe
       597│         path_list = map(fsencode, path_list)
       598│     for dir in path_list:
       599│         fullname = path.join(dir, file)
       600│         try:
    →  601│             exec_func(fullname, *argrest)
       602│         except (FileNotFoundError, NotADirectoryError) as e:
       603│             last_exc = e
       604│         except OSError as e:
       605│             last_exc = e

```

A little bit googling didn't provided any helpful results. Any idea what could be the problem?

Using python version 3.8.10 on Ubuntu 20.04.

**Comment by KrazyKirby99999** [comment]
The instructions were incorrect. The correct command is `sudo python -m poetry run main.py`. The readme has been changed to reflect this.

**Comment by mikedolx** [comment]
I'm sorry, it still seems to be wrong. The "corrected" command from the README is `python -m poetry python run main.py` which gives me `The command "python" is not defined.`.

**Comment by mikedolx** [comment]
If i run it with `sudo poetry run python main.py` i get the following error message:

```
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    main()
  File "main.py", line 28, in main
    bot.run()
  File "/root/.cache/pypoetry/virtualenvs/matrix-matrix-bridge-R9GnFoV_-py3.8/lib/python3.8/site-packages/simplematrixbotlib/bot.py", line 84, in run
    asyncio.run(self.main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/.cache/pypoetry/virtualenvs/matrix-matrix-bridge-R9GnFoV_-py3.8/lib/python3.8/site-packages/simplematrixbotlib/bot.py", line 46, in main
    raise ValueError("Invalid Homeserver")
```
My homeserver is define as follows (in my config.toml):

`homeserver = "https://matrix.mydomain.de:443" #  my server is running under the ssl port 443.`

**Comment by KrazyKirby99999** [comment]
This function is used to check if a homeserver is invalid, https://github.com/i10b/simplematrixbotlib/blob/562f5775dd1d6fe1bbd26b188c7c8b6961177fb4/simplematrixbotlib/api.py#L90

**Comment by KrazyKirby99999** [comment]
Does the following path not work with your homeserver?
```python
f'{homeserver}/_matrix/client/versions'
```

**Comment by mikedolx** [comment]
The path you mentioned returns this:

I am using the non-delegated subdomain https://matrix.mydomain.com.

```
{
  "versions": [
    "r0.0.1",
    "r0.1.0",
    "r0.2.0",
    "r0.3.0",
    "r0.4.0",
    "r0.5.0",
    "r0.6.0",
    "r0.6.1"
  ],
  "unstable_features": {
    "org.matrix.label_based_filtering": true,
    "org.matrix.e2e_cross_signing": true,
    "org.matrix.msc2432": true,
    "uk.half-shot.msc2666": true,
    "io.element.e2ee_forced.public": false,
    "io.element.e2ee_forced.private": false,
    "io.element.e2ee_forced.trusted_private": false,
    "org.matrix.msc3026.busy_presence": false,
    "org.matrix.msc2285": false,
    "org.matrix.msc2716": false,
    "org.matrix.msc3030": false
  }
}
```

Regarding delevation, the response to 

`https://mydomain.com/.well-known/matrix/server`

returns this:

```
{ 
"m.server": "matrix.mydomain.com:443" 
}
```

Not sure if this messes something up or if your code has an issue with the "custom" port 443.

As i am running the bridge within the same container as my matrix homeserver i also tried http://localhost but without any port. I might try some domain/port combinations.

**Comment by KrazyKirby99999** [comment]
This specifically is the part that is probably failing:
```python
async with aiohttp.ClientSession() as session:
            try:
                async with session.get(
                        f'{homeserver}/_matrix/client/versions') as response:
                    if response.status == 200:
                        return True
            except aiohttp.client_exceptions.ClientConnectorError:
                return False
```
The probable cases are either the bot cannot connect to the homeserver or the homeserver sends a response that is not 200.

**Comment by mikedolx** [comment]
Using curl to ask my server gets me this:

```
[michael@laptop ~]$ curl -I -POST https://matrix.mydomain.com/_matrix/client/versions
HTTP/1.1 200 OK
Date: Sun, 06 Mar 2022 00:58:06 GMT
Server: Synapse/1.52.0
Content-Type: application/json
Cache-Control: no-cache, no-store, must-revalidate
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: X-Requested-With, Content-Type, Authorization, Date
```
If you dm me, i can send you my server-address. Just don't want to post it here.

**Comment by KrazyKirby99999** [comment]
Would you mind joining the Matrix room? https://matrix.to/#/#simplematrixbotlib:matrix.org
